### PR TITLE
moved connection logic into connection Ops

### PR DESCRIPTION
**Pull request by jaberg**
If we move connection logic into their own Ops, then high level graph manipulation becomes a lot easier.  This PR doesn't have that manipulation code, but it moves some of the theano reshaping & stacking etc. from network.py into the body of new Ops in connection.py

### CODE REVIEW

**Comment by studywolf** [comment]
what's going on in the if statement on lines 53-54 of connection.py?

**Comment by jaberg** [comment]
cut and paste error.

What tests should I run as a basic smoke test of these changes?

**Comment by studywolf** [comment]
just a basic one that uses a slew of things would be the test_basal_ganglia.py file! 
should look like this at the end 
bg

**Comment by studywolf** [comment]
also I ran a couple of them myself and I think they're good to merge in, if there's nothing else you wanted to do on this one I can go ahead and do it

**Comment by tbekolay** [comment]
Since this is a pull request from a remote branch, it might be a bit more complicated. If it is, I can do the merge if it's ready.

**Comment by studywolf** [comment]
Actually it's pretty OK! There's that link next to the green button that walked me through getting it

**Comment by tbekolay** [comment]
Cool, yeah, I was just looking at that too! Handy.

**Comment by studywolf** [comment]
merged!

**Comment by tbekolay** [comment]
I think the second commit (https://github.com/jaberg/nengo_theano/commit/a3e09a4381450642d23cc723859215ead598770f) was missed.

**Comment by studywolf** [comment]
second attempt!

**Comment by tbekolay** [comment]
:+1:

**Pull request merged**
