### PR TITLE
ENH: python setup.py develop (via setuptools)

### PR DESCRIPTION
**Pull request by jaberg**
Not sure where we left off re: linear history / PRs, but I wanted to suggest using setuptools so that I can do in-place installs via `python setup.py develop`

### CODE REVIEW

**Comment by tbekolay** [comment]
Sounds good to me. Any objections?

**Comment by jaberg** [comment]
@tbekolay how do we go about merging this? Green button is OK? or merge commit is unwelcome?

In Theano we have a convention of never merging our own commits, which goes a long way to spreading around the knowledge of the code base.

**Comment by tbekolay** [comment]
I'll merge it in; not merging our own commits sounds like a good policy! We'll talk about it at the sprint for sure.

**Comment by tbekolay** [comment]
Merged!

**Pull request closed without merging**
