### PR TITLE
Removed open_cl business

### PR DESCRIPTION
**Pull request by studywolf**
Since it looks like the open_cl approach needs to involve lots of rewriting, removed it from here to try and keep a more straightforward theano implementation. 

This is a modification of an earlier commit, @tbekolay what's the best way to have this branch overwrite the current master branch?

### CODE REVIEW

**Comment by tbekolay** [comment]
Is the earlier commit on master? If so, you can't modify it. That's what all these rules were for, so that we never have to rewrite history on master. Just make the modifications that you want to make as a separate commit.

Also, quick query as to why move examples into the `nengo` package?

**Comment by studywolf** [comment]
yeah the changes are too many to really go back through and undo them all, i could just do a hard push, right? I know it messes up the history, but ... i don't know, could i rebase the master branch to this branch and then push it? would that work? 

also moved the examples folder so they could run, the imports were all weird and now they're the same as the tests and templates!

**Comment by tbekolay** [comment]
If you can rebase the changes, you can easily revert them. Use [git revert](https://www.kernel.org/pub/software/scm/git/docs/git-revert.html); it does exactly this thing, but by introducing new commits instead of wiping out old commits. Don't do a hard push, as it means that James's and any other fork gets hosed. There's no way to change the master's history without hosing forks, or anyone who's cloned the repository locally.

The idea with having an examples folder external from `nengo` is that it's not part of the `nengo` namespace, so it would (as you want examples to do) import nengo the same way that someone else's script would import them. Tests can import them using relative imports (the `from .. import Model` stuff), but examples shouldn't use that syntax because users using those examples would have to change them.

**Comment by tbekolay** [comment]
If you're having trouble getting the examples to run, you probably just have to install nengo (`python setup.py install` in the root directory).

**Comment by studywolf** [comment]
ok, so i'll get revert the master, then rebase new_master, then i should be able to push without messing up the history?

**Pull request closed without merging**
