### PR TITLE
Learn fix

### PR DESCRIPTION
**Pull request by studywolf**
fixed some of the transposing etc in learning, problem previously showed up when connecting two populations of different sizes. also updated the scripts folder

### CODE REVIEW

**Comment by studywolf** [comment]
@tbekolay could i get a merge, kind sir?

**Comment by tbekolay** [comment]
Yeah for sure. We should have some way of differentiating pull requests that are works in progress from those that are ready to be merged, perhaps...

**Comment by studywolf** [comment]
Ah good point, maybe it would be a comment here saying "ready to merge" or something

**Comment by tbekolay** [comment]
Yeah, or by default things are ready to merge unless they say "Work in progress" or "WIP" in the subject or something?

**Comment by studywolf** [comment]
Yeah that would make sense to me!

**Comment by tbekolay** [comment]
Merged. Even got rid of that winky face for ya.

**Pull request closed without merging**
