### PR TITLE
Reduced A matrix gen time

### PR DESCRIPTION
**Pull request by studywolf**
Dropped the gen time a fair amount, without suffering performance drop.

### CODE REVIEW

**Comment by jaberg** [comment]
Good idea, but this constant depends on the function being learned, and the size of the ensemble, in theory right? So maybe the multipliers should not be hard-coded?

**Comment by studywolf** [comment]
Hmm, I don't think so. The time used to be hardcoded at 1 second and .05 seconds, I just dropped it to be 10 and 200 \* dt, which just from running several of the tests didn't introduce any drop in performance. It defs shouldn't affect learning, because this compute decoders isn't used with learning. And the function isn't an issue at this point as we're just sampling the average firing rate of the neurons given different input currents. 
I beeeeliiieeeeeevvve that regardless of the size of the ensemble the signal should converge in roughly the same amount of time, I could try running the other tests though or examples.

**Comment by jaberg** [comment]
OK. I'm pretty sure that the amount of data you need to fit a function
depends on the complexity of the function, but maybe that doesn't really
matter enough here to warrant an interface change.

**Comment by tbekolay** [comment]
Yeah, this is just simulating a neuron with constant J for a bit, so it shouldn't be affected by the function or ensemble size.

**Comment by studywolf** [comment]
Ah I see what you're saying james, but that's related to the number of sample points that you have, not the time of simulation. In general we use 500, which seems to be enough, but this is also why applying learning you can get better results than with the least squares calculation.

edit: this is just dealing with the accuracy of your data at each of the sample points, and the reduced sim times seem to be as accurate!

**Comment by studywolf** [comment]
sooo, can someone merge this?

**Comment by tbekolay** [comment]
Sure, just a sec.

**Comment by tbekolay** [comment]
Merged!

**Comment by studywolf** [comment]
sweeet thanks

**Pull request closed without merging**
